from django.urls import path
from . import views
urlpatterns = [
     path('user-profile/', views.UserProfileView.as_view(), name ='home'),
     path('logout/', views.LogoutView.as_view(), name ='logout'),
     path('register/', views.UserRegistrationView.as_view(), name='register'),
     path('add-faculty/', views.FacultyView.as_view(), name ='add-faculty'),
     path('get-department/', views.DepartmentView.as_view(), name ='get-department'),
     path("add-student/", views.add_student, name="add-student"),
     path("get-programme/", views.get_programmes, name="get-programmes"),
     path("get-level/", views.get_levels, name="get-levels"),
     path("get-faculty/", views.get_faculty, name="get-faculty"),
     path('faculties/edit/<int:faculty_id>/', views.edit_faculty, name='edit-faculty'),
     path('faculties/delete/<int:faculty_id>/', views.delete_faculty, name='delete-faculty'),
     path('faculties/<int:faculty_id>/', views.get_faculty_details, name='get-faculty-details'),
     path("add-course/", views.CourseView.as_view(), name="add-course"),
     path("courses/edit/<int:course_id>/", views.edit_course, name="edit-course"),
     path("courses/delete/<int:course_id>/", views.delete_course, name="delete-course"),
     path("get-courses/", views.get_courses, name="get-courses"),
     path("courses/<int:course_id>/", views.get_course_details, name="get-course-details"),
     path('add-batch/', views.add_batch, name='add_batch'),
     path('batches/edit/<int:batch_id>/', views.edit_batch, name='edit_batch'),
     path('batches/delete/<int:batch_id>/', views.delete_batch, name='delete_batch'),
     path('get-batches/', views.get_batches, name='get_batches'),
     path('batches/<int:batch_id>/', views.get_batch_details, name='get_batch_details'),
     path('add-programme/', views.ProgrammeView.as_view(), name='add_programme'),
     path('programme/edit/<int:programme_id>/', views.edit_programme, name='edit_programme'),
     path('programme/<int:programme_id>/delete/', views.delete_programme, name='delete_programme'),
     path('get-programme/', views.get_programmes, name='get_programmes'),
     path('programme/<int:programme_id>/', views.get_programme_details, name='get_programme_details'),
]